# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master
    steps: 
      - checkout 
      - run: 
          name: Run version check
          command: |
            gridlabd --version
            gridlabd --origin
      - run:
          name: Run the simulation
          command: |
            git clone https://github.com/dchassin/gridlabd.git
            mv -f config/local.glm gridlabd/models/ieee123/config/
            more gridlabd/models/ieee123/config/local.glm
            cd gridlabd/models/ieee123
            gridlabd model/ieee123.glm
      - store_artifacts: 
            path: /root/project/gridlabd/models/ieee123/output
